version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"

  fastapi:
    build: .
    container_name: fastapi-container
    depends_on:
      - redis
    ports:
      - "5556:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  celery:
    build: .
    container_name: celery-container
    depends_on:
      - redis
    command: celery -A tasks worker --loglevel=info --concurrency=200

  flower:
    build: .
    container_name: flower-container
    depends_on:
      - redis
    command: celery -A tasks flower --port=5555
    ports:
      - "5555:5555"
